### ISSUE TITLE
Uncaught DOMException (Possible wrong HTML example code)

### ISSUE THREAD

**Issue by schonhose** [fralonra/basketball-court#2]
With the following HTML code I get a `Uncaught DOMException: An attempt was made to create or change an object in a way which is incorrect with regard to namespaces`.

```
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>SVG basketball court</title>
  <meta name="description" content="court">
  <script type='text/javascript' src="basketball-court.min.js"></script>
  <script type='text/javascript'>
	const element = basketballCourt({
		horizontal: true,
	}).toDom()
	document.body.appendChild(element)
  </script>
</head>

<body>
	<h1>example</h1>
</body>
</html>
```

**Comment by fralonra** [comment]
Thanks for your reporting!

It turns out to be that setting `xmlns` using `setAttributeNS` on svg tag should use the namespace `'http://www.w3.org/2000/xmlns/'`.
I've committed a quick fix and published to v1.1.2.

More tests should be added in the future.
